### PR TITLE
Updated llama-cpp-python (and its dependencies with env variables)

### PR DESCRIPTION
**Pull request by SnehalSwadhin**
Updated llama-cpp-python to 0.3.1 using Pypi.

Conda had 0.2.24 as the latest version. I was not able to run any ChatModel in langchain in this version (was getting an error that Llama.create_chat_completion() got an unexpected keyword argument 'logprobs')

I had to add a few environment variables and dependencies for updating llama-cpp-python

### CODE REVIEW

**Comment by klwetstone** [comment]
@SnehalSwadhin This represents a major change to the existing dependencies. Are you certain that `llama-cpp-python` 0.2.24 cannot be used for your solution? Is it possible to debug or work around the error in 0.2.24?

If not, it will take us some time to determine if all of these changes are compatible with solutions that worked in the previous runtime. This is a really impressive deep dive into advanced package installation with pixi 👏

**Comment by SnehalSwadhin** [comment]
I was able to get results with structured_structured output in langchain pretty easily with ollama (about a week). Just using llama.cpp has been a pain for more than a month now. I actually gave up at some point😅, but came back today to give it a last try. 

Because it works on my device, its very difficult to debug. And I was not able to find any other fix for: Llama.create_chat_completion() got an unexpected keyword argument 'logprobs'

Anyway, it was fun figuring out something new🙌

**Comment by SnehalSwadhin** [comment]
At this point I just want to see one of my submission run successfully. Though the sad part is that it probably does not score as high as some submissions on the leaderboard.

**Comment by klwetstone** [comment]
If the change would be important to your solution we can certainly consider, just let me know!

I also enjoyed reading the PR -- this is the first competition for which we've used Pixi to manage dependencies, and your code uses a lot Pixi functionality that I hadn't seen before.

In case you hadn't seen it, there is a second DrivenData [competition](https://www.drivendata.org/competitions/296/cdc-novel-variables/) that uses the same data, but is an unsupervised challenge that does not rely on code execution for submissions. If you're interested, you could experiment with some of these methods for that challenge.

**Comment by SnehalSwadhin** [comment]
I've got a teammate working on the second track.
Let me try one more day with llama-cpp-python 0.2.24
If it still doesn't work, I'll tag you here.

**Comment by SnehalSwadhin** [comment]
@klwetstone Although I managed to bypass the `logprobs` error by overriding a method in ChatLlamaCpp, but my code ultimately does not seem to work in 0.2.24. Though it works without any issue in the newer version.

Invoking any llm with structured_output only returns `None`. I tried many combinations of different prompts, old & new models (mistral, meta-llama, granite, dolphin), and even tried the basic `LamaCpp` (non chat_models).

I'd request you to try and update the library. 
If it seem to go beyond the rules of the competition, please do let me know. I appreciate your cooperation.

**Comment by klwetstone** [comment]
HI @SnehalSwadhin. Unfortunately, we are not able to support changes to the runtime that would break existing submissions. Since we already had `llama-cpp-python` 0.2.24 as part of the runtime, changing it to 0.3.1 would risk breaking existing submissions. We should have flagged when you first submitted your PR, and deeply apologize for the inconvenience to your team. It is a well constructed PR, and I applaud your team for finding clever workarounds in the `pixi.toml` file.

I’m closing this PR, since we’re unable to support `llama-cpp-python` 0.3.1. Good luck, and our apologies once again for the inconvenience.

**Comment by klwetstone** [comment]
HI @SnehalSwadhin. Unfortunately, we are not able to support changes to the runtime that would break existing submissions. Since we already had `llama-cpp-python` 0.2.24 as part of the runtime, changing it to 0.3.1 would risk breaking existing submissions. We should have flagged when you first submitted your PR, and deeply apologize for the inconvenience to your team. It is a well constructed PR, and I applaud your team for finding clever workarounds in the `pixi.toml` file.

I’m closing this PR, since we’re unable to support `llama-cpp-python` 0.3.1. Good luck, and our apologies once again for the inconvenience.
